Update Indonesia Translation
ImranR98/Obtainium pull request #1868
Opened 2024-10-01 03:01 UTC by kuchingneko28

Corrected several words

2024-10-01 15:07 UTC, robifr commented
i guess it's better for us to get into discussion.

2024-10-01 18:23 UTC, robifr requested changes
i can't comment for every lines as most of the reason are same. however, the previous translation aims to sounds more natural to our user. most of the translation are misleading too. 

there are some stuff to do after reviewing this PR. 
- improve "rate limit" term by checking for how other app/project use the term to make it consistent with others.
- check whether "input" is a proper term in indonesian KBBI or not, to improve line 95.

2024-10-01 18:23 UTC, robifr commented on assets/translations/id.json
> +    "defaultPseudoVersioningMethod": "Metode Penomoran Versi Semu",
you forgot the "standard" part. albeit i was thinking about "metode standar dalam penomoran versi semu" is actually better, but it's mouthful. so keep as is i guess.

2024-10-01 18:23 UTC, robifr commented on assets/translations/id.json
> +        "other": "{} dan {} aplikasi lainnya memiliki pembaruan."
agree for this one, because it's either "mendapatkan" or "memiliki".

2024-10-01 21:18 UTC, ImranR98 commented
Will wait for their response.

2024-10-02 01:02 UTC, kuchingneko28 commented
> i can't comment for every lines as most of the reason are same. however, the previous translation aims to sounds more natural to our user. most of the translation are misleading too.
> 
> there are some stuff to do after reviewing this PR.
> 
> * improve "rate limit" term by checking for how other app/project use the term to make it consistent with others.
> * check whether "input" is a proper term in indonesian KBBI or not, to improve line 95.

I was trying to keep it consistent with the words used, simplifying it while preserving the context. If you find any text that feels incorrect, feel free to change it

2024-10-02 05:45 UTC, closed without merging