Add an amoled black theme
ImranR98/Obtainium pull request #465
Opened 2023-04-13 11:20 UTC by Bnyro

This PR adds a switch to enable a pure black (amoled) theme, works for both the Obtainium and the Material You theme.

closes #155

2023-04-13 14:28 UTC, ImranR98 requested changes
Thanks for the PR! Just a few comments to review.

2023-04-13 14:28 UTC, ImranR98 commented on assets/translations/en.json
> +    "amoledTheme": "Pure black theme",
Could you change this to "Use pure black dark theme" - this makes it more obvious that the toggle will only have an effect when the dark theme is on.

The key (`amoledTheme`) should also be closer to the value. Maybe `useBlackTheme`?

Also please add to all other language files (re-use the English version as a placeholder for others to update later).

2023-04-13 14:28 UTC, ImranR98 commented on lib/pages/settings.dart
> +                            Row(
This should be directly below the `themeDropdown` as the two settings are related.

2023-04-13 14:28 UTC, ImranR98 commented on lib/pages/settings.dart
> +                            height16,
`height16` won't be necessary anymore as the `colourDropdown` has enough space above it.

2023-04-13 16:21 UTC, Bnyro commented
Thanks for the review, I force pushed the suggested changes!

2023-04-14 02:59 UTC, ImranR98 approved these changes

2023-04-14 02:59 UTC, merged